apiVersion: v1
kind: Secret
metadata:
  labels:
    app: library-shop
    group: rhacademy
  name: library-shop
type: Opaque
stringData:
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://library-db:5432/library-db
  QUARKUS_DATASOURCE_PASSWORD: library-pwd
  QUARKUS_DATASOURCE_USERNAME: library-user